import Head from "next/head";
import styles from "../styles/Home.module.css";
import Banner from "../components/Banner";
import NavBar from "../components/NavBar";
import SectionCard from "../components/Card/SectionCard";
import { getVideos, getMostPopularVideos } from "../lib/index";

export async function getServerSideProps() {
  const disneyVideos = await getVideos("disneyTrailer");
  const bestAnime = await getVideos("bestAnime");
  const marvelMovies = await getVideos("marvelMovies");
  const Popular = await getMostPopularVideos();

  //  Promise.all([
  //     getVideos("disneyTrailer"),
  //     getVideos("bestAnime"),
  //     getVideos("marvelMovies"),
  //     getMostPopularVideos(),
  //   ]).then((responses) => {
  //     console.log(responses)

  //   })
  // ssr
  return { props: { disneyVideos, Popular, bestAnime, marvelMovies } };
}

export default function Home({
  disneyVideos,
  popular,
  bestAnime,
  marvelMovies,
}) {
  // console.log(data)

  return (
    <div className={styles.container}>
      <Head>
        <title>Nel-Prix</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className={styles.main}>
        <NavBar username="JLML" />
        <Banner
          title="Demon Slayer"
          subtitle="Let the hunting begin..."
          imgUrl={
            "https://www.cheatsheet.com/wp-content/uploads/2021/11/Demon-Slayer-Entertainment-District.jpeg"
          }
        />
        <div className={styles.sectionWrapper}>
          <SectionCard title="Disney" videos={disneyVideos} size="large" />
          <SectionCard title="Best Anime" videos={bestAnime} size="small" />
          <SectionCard
            title="Marvel Movies"
            videos={marvelMovies}
            size="medium"
          />
          <SectionCard title="Popular" videos={popular} size="small" />
        </div>
      </div>
    </div>
  );
}
