import Head from "next/head";
import styles from "../styles/Home.module.css";
import Banner from "../components/Banner";
import NavBar from "../components/NavBar";
import SectionCard from "../components/Card/SectionCard";
import { getVideos, getMostPopularVideos, watchItAgainVideos } from "../lib/index";

export async function getServerSideProps() {
  
  const token =
    "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3N1ZXIiOiJkaWQ6ZXRocjoweDdENEQ3RjRGZjcyMjZmOTAwRGUyMDAxRENmNDA3OWFCOGJFOWIwYzgiLCJlbWFpbCI6Im1lamlhbGFndW5hQHlhaG9vLmNvbSIsInB1YmxpY0FkZHJlc3MiOiIweDdENEQ3RjRGZjcyMjZmOTAwRGUyMDAxRENmNDA3OWFCOGJFOWIwYzgiLCJpYXQiOjE2NDc5NjAxOTEsImV4cCI6MTY0ODU2NDk5MSwiaHR0cHM6Ly9oYXN1cmEuaW8vand0L2NsYWltcyI6eyJ4LWhhc3VyYS1hbGxvd2VkLXJvbGVzIjpbInVzZXIiLCJhZG1pbiJdLCJ4LWhhc3VyYS1kZWZhdWx0LXJvbGUiOiJ1c2VyIiwieC1oYXN1cmEtdXNlci1pZCI6ImRpZDpldGhyOjB4N0Q0RDdGNEZmNzIyNmY5MDBEZTIwMDFEQ2Y0MDc5YUI4YkU5YjBjOCJ9fQ.DxiatwXB2dCfuCbN9t4PEV7XUbP1gO0Kwb73O_KaLnc";
  const userId = "did:ethr:0x7D4D7F4Ff7226f900De2001DCf4079aB8bE9b0c8";

  const watchAgainVideos = await watchItAgainVideos(userId , token)
  const disneyVideos = await getVideos("disneyTrailer");
  const bestAnime = await getVideos("bestAnime");
  const marvelMovies = await getVideos("marvelMovies");
  const Popular = await getMostPopularVideos();

  console.log("line 20------------------------",{watchAgainVideos})
  // ssr
  return {
    props: {
      disneyVideos,
      Popular,
      bestAnime,
      marvelMovies,
      watchAgainVideos,
    },
  };
}

export default function Home({
  disneyVideos,
  popular,
  bestAnime,
  marvelMovies,
  watchAgainVideos,
}) {
  console.log("-----------------line40", {watchAgainVideos})

  return (
    <div className={styles.container}>
      <Head>
        <title>Nel-Prix</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className={styles.main}>
        <NavBar username="JLML" />
        <Banner
          videoId={"jiJu4K2jems"}
          title="Demon Slayer"
          subtitle="Let the hunting begin..."
          imgUrl={
            "https://www.cheatsheet.com/wp-content/uploads/2021/11/Demon-Slayer-Entertainment-District.jpeg"
          }
        />
        <div className={styles.sectionWrapper}>
          <SectionCard title="Disney" videos={disneyVideos} size="large" />
          <SectionCard
            title="watch it again"
            videos={watchAgainVideos}
            size="small"
          />
          <SectionCard title="Best Anime" videos={bestAnime} size="small" />
          <SectionCard
            title="Marvel Movies"
            videos={marvelMovies}
            size="medium"
          />
          <SectionCard title="Popular" videos={popular} size="small" />
        </div>
      </div>
    </div>
  );
}
