import Head from "next/head";
import styles from "../styles/Home.module.css";
import Banner from "../components/Banner";
import NavBar from "../components/NavBar";
import SectionCard from "../components/Card/SectionCard";
import {getVideos , getMostPopularVideos} from "../lib/index";

export async function getServerSideProps() {
  const disneyVideos = await getVideos("disney trailer");
  const bestAnime = await getVideos("best animes");
  const marvelMovies = await getVideos("marvel movies");
  const Popular = await getMostPopularVideos("most Popular");

  // ssr
  return { props: { disneyVideos, Popular, bestAnime, marvelMovies } };
}

export default function Home({ disneyVideos, Popular , bestAnime , marvelMovies}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Nel-Prix</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <NavBar username="JLML" />
      <Banner
        title="Demon Slayer"
        subtitle="Let the hunting begin..."
        imgUrl={
          "https://www.cheatsheet.com/wp-content/uploads/2021/11/Demon-Slayer-Entertainment-District.jpeg"
        }
      />
      <div className={styles.sectionWrapper}>
        <SectionCard title="Disney" videos={disneyVideos} size="large" />
        <SectionCard title="Best Anime" videos={bestAnime} size="small" />
        <SectionCard title="Marvel Movies" videos={marvelMovies} size="medium" />
        <SectionCard title="Popular" videos={Popular} size="small" />
      </div>
    </div>
  );
}
